### ISSUE TITLE
Azure 환경 설정

### ISSUE THREAD

**Issue by geunho** [hypergamma/instance-controller#1]
#### TODOs
- [x] docker cluster vm 생성
- [x] docker engine, docker compose, swarm 설치
- [x] docker cluster vm 복제
- [x] tsdb vm 생성
- [x] controller vm 생성
- [x] observer vm 생성
- [x] mariadb vm 생성
- [x] admin vm 생성
- [x] Influxdb, grafana 설치
- [x] docker cluster vm 에 telegraf 설치

#### VM List
역할 | vm 명 | 수량
------------ | ------------- | -------------
docker cluster | gamma-dc{01-10} | 10
admin | gamma-admin | 1
mariadb | gamma-sql | 1
tsdb | gamma-tsdb | 1
controller | gamma-controller | 1
observer | gamma-observer | 1

총 15 대

**Comment by geunho** [comment]
docker cluster vms 생성시 1대 설정 후 복제 진행할 것.

**Comment by geunho** [comment]
docker vm은 일본 동부에 최초 생성했는데 최대로 생성할 수 있는 vm 수 (20개) 가 도달하여 한 대 밖에 생성 못 함.
tsdb vm 은 동남 아시아로 선택.
docker vm 이전이 필요함. (복잡하다면 그냥 새로 설치하는걸로....)

**Comment by cacaocake** [comment]
진짜 사용 가능한 지역이 넘나 좁음 -_-

**Comment by cacaocake** [comment]
mariadb 만들었음
계정은 root 하나고 비번은 slack에...

**Comment by cacaocake** [comment]
admin에 nvm, npm, yarn 설치함

**Comment by geunho** [comment]
vm 복제 방법을 아직 찾지 못 함.
vm 하나하나 생성 후 docker 설치 진행할 것.

**Comment by geunho** [comment]
핵노가다 손 복제 완료.

**Comment by geunho** [comment]
#### docker cluster info
host | ip | url
---- | -- | ---
gamma-dc01 | 52.185.151.222 | tcp://52.185.151.222:2376
gamma-dc02 | 13.76.246.233 | tcp://13.76.246.233:2376
gamma-dc03 | 52.163.60.150 | tcp://52.163.60.150:2376
gamma-dc04 | 52.187.40.252 | tcp://52.187.40.252:2376
gamma-dc05 | 52.163.62.148 | tcp://52.163.62.148:2376
gamma-dc06 | 13.76.246.135 | tcp://13.76.246.135:2376
gamma-dc07 | 207.46.226.210 | tcp://207.46.226.210:2376
gamma-dc08 | 52.163.94.98 |  tcp://52.163.94.98:2376
gamma-dc09 | 13.76.142.26 | tcp://13.76.142.26:2376
gamma-dc10 | 52.187.46.38 | tcp://52.187.46.38:2376
