### ISSUE TITLE
개발 환경 설정 및 솔루션 검증

### ISSUE THREAD

**Issue by geunho** [hypergamma/instance-controller#2]
#### TODOs
- [x] 프로젝트 구조 생성
- [x] 솔루션 및 라이브러리 선정
- [x] 검증 코드 작성 및 테스트

#### Features
- registry 저장소 읽기/쓰기
- admin 저장소 읽기/쓰기
- rest api server

**Comment by geunho** [comment]
registry kvdb는 redis로 확정.

**redis info**
- hostname: gamma-observer
- endpoint: 52.187.36.188:6379
