### ISSUE TITLE
Observer 개발

### ISSUE THREAD

**Issue by geunho** [hypergamma/instance-controller#3]
#### TODOs
- [x] influx repo 모듈 작성
- [x] controller repo 모듈 작성
- [x] 메인 app.js 골격 생성

#### 고려 사항
- 함수별로 observer를 생성
- dockerize, 함수 생성/삭제시 observer 등록/제거
- 주기적인 조회를 통해 리소스 확인
- 룰 정의
- 룰에 따라 controller 호출을 통해 swarm의 instance 수 조정
